# -*- coding: utf-8 -*-
"""CO5430_melanoma_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmVIO5X7C7aAxkWSapuOnZy7IX18T9hl

# CO5430 Melanoma Classification — Baseline Pipeline
Run each cell in order, top to bottom.

### Step 1: Install and download the dataset
"""

!pip install kaggle -q
!mkdir -p ~/.kaggle
!echo "PASTE_YOUR_NEW_TOKEN_HERE" > ~/.kaggle/access_token
!chmod 600 ~/.kaggle/access_token

!kaggle datasets download -d bhaveshmittal/melanoma-cancer-dataset -p /content/data --unzip

"""### Step 2: Find the actual train/test folders (handles any nesting)"""

import os

def find_dir(root, target_name):
    for dirpath, dirnames, _ in os.walk(root):
        if target_name in dirnames:
            return os.path.join(dirpath, target_name)
    return None

path = find_dir('/content/data', 'train')
valPath = find_dir('/content/data', 'test')

print('train path:', path)
print('test path:', valPath)

if path is None or valPath is None:
    raise FileNotFoundError("Couldn't locate train/test folders — check !ls /content/data")

"""### Step 3: Imports"""

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import models, datasets, transforms
from torch.utils.data import DataLoader
from torch.cuda.amp import autocast, GradScaler
from torch.optim.lr_scheduler import ReduceLROnPlateau
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
from warnings import filterwarnings
filterwarnings('ignore')

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {device}')

"""### Step 4: Transforms and datasets"""

imgSize = 112

transformer = transforms.Compose([
    transforms.RandomRotation(degrees=20),
    transforms.RandomHorizontalFlip(p=0.3),
    transforms.RandomVerticalFlip(p=0.3),
    transforms.Resize(size=(imgSize, imgSize), antialias=True),
    transforms.CenterCrop(size=(imgSize, imgSize)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

valTransformer = transforms.Compose([
    transforms.Resize(size=(imgSize, imgSize), antialias=True),
    transforms.CenterCrop(size=(imgSize, imgSize)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

trainData = datasets.ImageFolder(root=path, transform=transformer)
valData = datasets.ImageFolder(root=valPath, transform=valTransformer)

print('Classes:', trainData.classes)

"""### Step 5: Class balance check (for the imbalance slide, and Step 8's pos_weight)"""

from collections import Counter
counts = Counter(trainData.targets)
print({trainData.classes[k]: v for k, v in counts.items()})

"""### Step 6: Data loaders"""

batchSize = 256

trainLoader = DataLoader(trainData, batch_size=batchSize, shuffle=True, num_workers=2)
valLoader = DataLoader(valData, batch_size=batchSize, shuffle=False, num_workers=2)

"""### Step 7: Model"""

model = models.efficientnet_v2_s(weights='DEFAULT')
model.classifier[1] = nn.Linear(model.classifier[1].in_features, 1)
model = model.to(device)

"""### Step 8: Loss, optimizer, scheduler (class-weighted for imbalance)"""

num_benign = counts[trainData.class_to_idx['benign']] if 'benign' in trainData.class_to_idx else list(counts.values())[0]
num_malignant = counts[trainData.class_to_idx['malignant']] if 'malignant' in trainData.class_to_idx else list(counts.values())[1]
pos_weight = torch.tensor([num_benign / num_malignant]).to(device)

criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)
optimizer = optim.Adam(model.parameters(), lr=0.001)
scheduler = ReduceLROnPlateau(optimizer, threshold=0.01, factor=0.1, patience=3, min_lr=1e-5)

"""### Step 9: Early stopping variables"""

patience = 5
minDelta = 0.01
currentPatience = 0
bestLoss = float('inf')

"""### Step 10: Training loop"""

scaler = GradScaler()
trainLosses, valLosses, valAccs = [], [], []
epochs = 10

for epoch in range(epochs):
    model.train()
    runningLoss = 0.0
    for inputs, labels in trainLoader:
        inputs, labels = inputs.to(device), labels.to(device)
        labels = labels.unsqueeze(1).float()

        optimizer.zero_grad()
        with autocast():
            outputs = model(inputs)
            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        runningLoss += loss.item()

    trainLoss = runningLoss / len(trainLoader)
    print(f'Epoch {epoch+1}/{epochs} - Training Loss: {trainLoss:.4f}')
    trainLosses.append(trainLoss)

    model.eval()
    with torch.no_grad():
        valLoss, correct, total = 0.0, 0, 0
        for inputs, labels in valLoader:
            inputs, labels = inputs.to(device), labels.to(device)
            labels = labels.unsqueeze(1).float()
            outputs = model(inputs)
            loss = criterion(outputs, labels)
            valLoss += loss.item()
            predicted = (torch.sigmoid(outputs) > 0.5).float()
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        avgLoss = valLoss / len(valLoader)
        accuracy = correct / total * 100
        print(f'Validation Loss: {avgLoss:.4f} | Validation Accuracy: {accuracy:.2f}%\n')
        valLosses.append(avgLoss)
        valAccs.append(accuracy)

        if avgLoss < bestLoss - minDelta:
            bestLoss = avgLoss
            currentPatience = 0
        else:
            currentPatience += 1
            if currentPatience >= patience:
                print('Early stopping triggered.')
                break

        scheduler.step(avgLoss)

"""### Step 11: Plot loss/accuracy curves"""

plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.plot(trainLosses, label='Training Loss')
plt.plot(valLosses, label='Validation Loss')
plt.xlabel('Epoch'); plt.ylabel('Loss'); plt.legend()

plt.subplot(1, 2, 2)
plt.plot(valAccs, label='Validation Accuracy')
plt.xlabel('Epoch'); plt.ylabel('Accuracy (%)'); plt.legend()
plt.show()

"""### Step 12: Confusion matrix"""

model.eval()
allLabels, allPreds = [], []
with torch.no_grad():
    for inputs, labels in valLoader:
        inputs, labels = inputs.to(device), labels.to(device)
        labels = labels.unsqueeze(1).float()
        outputs = model(inputs)
        predictions = (torch.sigmoid(outputs) > 0.5).float()
        allLabels.extend(labels.cpu().numpy())
        allPreds.extend(predictions.cpu().numpy())

allLabels = np.array(allLabels)
allPreds = np.array(allPreds)
matrix = confusion_matrix(allLabels, allPreds)

sns.heatmap(matrix, annot=True, fmt='d', cmap='Greens',
            xticklabels=valData.classes, yticklabels=valData.classes, cbar=False)
plt.title('Confusion Matrix - Validation Set')
plt.xlabel('Predicted Label'); plt.ylabel('True Label')
plt.show()